version: 2
project_name: linqora-host
builds:
  - dir: LinqoraHost
    main: ./cmd
    id: "linqora-host"
    binary: linqora
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
    ldflags:
      - -X LinqoraHost/internal/version.App={{.Version}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: '🚀 Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: '📦 Dependencies'
      regexp: "^.*chore\\(deps\\):.*$"
      order: 2
    - title: '📝 Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: 'Other'
      order: 999
