name: linqoraremote
description: "Tool for intelligent interaction with a computer"

publish_to: 'https://github.com/pasichDev/linqora'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  multicast_dns: ^0.3.2
  web_socket_channel: ^2.4.0
  network_info_plus: ^6.1.4
  loading_animation_widget: ^1.3.0
  device_info_plus: ^11.4.0
  fl_chart: ^0.71.0
  get_storage: ^2.1.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1
  package_info_plus: ^8.3.0
dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0


flutter:
  uses-material-design: true

platforms:
  android:
  ios: