// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchSystemInfo() {
  return window['go']['main']['App']['FetchSystemInfo']();
}

export function GetAllCPUMetrics() {
  return window['go']['main']['App']['GetAllCPUMetrics']();
}

export function GetAllRAMMetrics() {
  return window['go']['main']['App']['GetAllRAMMetrics']();
}
