// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {systeminfo} from '../models';
import {cpu} from '../models';
import {ram} from '../models';

export function FetchSystemInfo():Promise<systeminfo.SystemInfoInitial>;

export function GetAllCPUMetrics():Promise<cpu.CPUMetrics>;

export function GetAllRAMMetrics():Promise<ram.RAMMetrics>;
