// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {database} from '../models';

export function FetchSystemInfo():Promise<backend.SystemInfoInitial>;

export function GetAllCPUMetrics():Promise<database.CPUMetrics>;

export function GetAllRAMMetrics():Promise<database.RAMMetrics>;
